spring.application.name=msnotificacoes

server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# AWS
aws.ses.region=us-east-2
aws.ses.access-key=${AWS_ACCESS_KEY}
aws.ses.secret-key=${AWS_SECRET_KEY}
aws.ses.remetente=${AWS_SES_REMETENTE}
aws.ses.destinatario=${AWS_SES_DESTINATARIO}